
= Backend API Endpoints

The following is a list of the backend API endpoints for the application:

== Send a message

To send a message, use the following endpoint:

----
Request: POST http://localhost:30000/message
Payload: {
    "message": {
        "content": "hi"
    }
}
Response: 200 {
  "messages": [
    {
      "content": "hi",
      "role": "user"
    },
    {
      "content": "response.text",
      "role": "assistant"
    }
  ]
}
----

== Upload a file

To upload a file, use the following endpoint:

----
Request: POST http://localhost:30000/upload
Payload: {}
Response: 400 {
  "message": "No file part"
}
----

== Change the active model

To change the active model, use the following endpoint:

----
Request: POST http://localhost:30000/change_model
Payload: {
    "model_name": "test"
}
Response: 200 {
  "message": "Changed to model test"
}
----

== Save custom instructions

To save custom instructions, use the following endpoint:

----
Request: POST http://localhost:30000/custom_instructions
Payload: {
    "example_request": "Your example request here",
    "example_response": "Your example response here"
}
Response: 200 {
  "message": "Custom instructions saved successfully"
}
----

== Get all the conversation names

To get all the conversation names, use the following endpoint:

----
Request: GET http://localhost:30000/conversations
Response: 200 {
  "conversation_names": [
    "hi"
  ]
}
----

== Check if the server is running

To check if the server is running, use the following endpoint:

----
Request: GET http://localhost:30000/
Response: 200 {
  "messages": "Server is running!"
}
----

== Get messages of a conversation

To get the messages of a conversation, use the following endpoint:

----
Request: GET http://localhost:30000/conversations/hi
Response: 200 {
  "conversation_messages": [
    {
      "content": "Your example request here",
      "role": "user"
    },
    {
      "content": "Your example response here",
      "role": "assistant"
    }
  ]
}
----

== Get all the model names

To get all the model names, use the following endpoint:

----
Request: GET http://localhost:30000/get_models
Response: 200 [
  "gpt",
  "test"
]
----

== Restart the server

To restart the server, use the following endpoint:

----
Request: GET http://localhost:30000/restartServer
Response: 200 {
  "message": "Server restarted successfully"
}
----

== Download the database ZIP file

To download the database ZIP file, use the following endpoint:

----
Request: GET http://localhost:30000/downloadDB
Response: 200 {db file}
----
