apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app-container
        image: chat_py:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: GOOGLE_SERVICE_ACCOUNT_JSON_BASE64
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: GOOGLE.json
