apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  namespace: chat-app
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  selector:
    app: chat-app
